name: Liblouis*
description: An open-source braille translator and back-translator.
markdown: kramdown
highlighter: pygments
url: http://www.liblouis.org
baseurl: ""
gems:
  - jekyll-sitemap
exclude: 
  - README.md