name: Liblouis*
description: An open-source braille translator and back-translator.
markdown: kramdown
highlighter: pygments
url: http://www.liblouis.org
baseurl: ""
gems:
  - jekyll-sitemap
exclude: 
  - README.md
defaults:
  - 
    scope:
      path: "" # all pages should have layout default by default
      type: "pages"
    values:
      layout: "default"
  - 
    scope:
      path: "" # all posts should have layout post by default
      type: "posts"
    values:
      layout: "post"
      tags: "Liblouis"
